"""Deterministic diagnostic and verification foundation."""

from .assets import AssetScanLimits, detect_repository_assets
from .dependencies import (
    DependencyDiagnosticError,
    PipDiagnosticRunner,
    compare_imports_to_requirements,
    detect_python_imports,
    parse_pip_check,
    parse_pip_inspect,
    parse_pip_report,
    parse_requirements_text,
    requirement_marker_applies,
    version_satisfies,
)
from .environment import (
    EnvironmentFingerprintError,
    collect_environment_fingerprint,
    parse_environment_fingerprint,
)
from .evidence import (
    EvidenceBuilder,
    EvidenceLimits,
    failure_signature,
    normalize_error_signature,
)
from .models import (
    AssetKind,
    AssetReference,
    DiagnosticContext,
    DiagnosticEvidenceItem,
    EnvironmentFingerprint,
    EnvironmentPackage,
    EvidenceKind,
    FailureClass,
    ImportDependencyFinding,
    ImportRecord,
    NormalizedFailure,
    PackageRecord,
    PipCheckIssue,
    PipInspectReport,
    PipReport,
    RepositoryAssets,
    RequirementParseResult,
    RequirementRecord,
    VerificationContract,
    VerificationTarget,
    VerificationTargetType,
)
from .normalizer import classify_failure, normalize_failure
from .verification import contract_from_plan

__all__ = [
    "AssetKind",
    "AssetReference",
    "AssetScanLimits",
    "DependencyDiagnosticError",
    "DiagnosticContext",
    "DiagnosticEvidenceItem",
    "EnvironmentFingerprint",
    "EnvironmentFingerprintError",
    "EnvironmentPackage",
    "EvidenceBuilder",
    "EvidenceKind",
    "EvidenceLimits",
    "FailureClass",
    "ImportDependencyFinding",
    "ImportRecord",
    "NormalizedFailure",
    "PackageRecord",
    "PipCheckIssue",
    "PipDiagnosticRunner",
    "PipInspectReport",
    "PipReport",
    "RepositoryAssets",
    "RequirementParseResult",
    "RequirementRecord",
    "VerificationContract",
    "VerificationTarget",
    "VerificationTargetType",
    "classify_failure",
    "collect_environment_fingerprint",
    "compare_imports_to_requirements",
    "contract_from_plan",
    "detect_python_imports",
    "detect_repository_assets",
    "failure_signature",
    "normalize_error_signature",
    "normalize_failure",
    "parse_environment_fingerprint",
    "parse_pip_check",
    "parse_pip_inspect",
    "parse_pip_report",
    "parse_requirements_text",
    "requirement_marker_applies",
    "version_satisfies",
]
